name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Package Caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Verify
        run: ./mvnw clean verify -B -U
  snapshot:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.repository_owner == 'atleon' && github.ref == 'refs/heads/main'
    name: Publish SNAPSHOT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Package Caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Publish SNAPSHOT Artifacts
        run: ./mvnw deploy --settings ./.mvn/settings/mvn-settings.xml -B -U -P oss-snapshot -DskipTests=true
        env:
          MAVEN_CENTRAL_TOKEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
